joy_node:
  ros__parameters:
    dev: "/dev/input/js0"
    deadzone: 0.05
    autorepeat_rate: 20.0

teleop_twist_joy_node:
  ros__parameters:
    axis_linear:
      x: 1
    scale_linear:
      x: -1.0
    axis_angular:
      yaw: 0
    scale_angular:
      yaw: -1.0
    enable_button: 0
    require_enable_button: true
